// Portuguese anatomical vocabulary, for deriving a name when no verified one
// exists. This is a lexicon plus gender, not a translator: the derivation in
// pt-derive.mjs is purely mechanical, and anything it produces is marked as
// derived in the atlas so the interface can say so.
//
// Nouns carry their gender ('m' or 'f') because the adjectives have to agree.
// Adjectives are listed as [masculine, feminine]; a single string means the
// form is invariant (lateral, renal, segmentar).

// Multi-word terms first: these are matched before the word-by-word pass, so
// "biceps brachii" does not come out as two unknown Latin words.
export const COMPOUNDS = {
  'biceps brachii': ['bíceps braquial', 'm'],
  'triceps brachii': ['tríceps braquial', 'm'],
  'brachialis': ['braquial', 'm'],
  'latissimus dorsi': ['grande dorsal', 'm'],
  'rectus abdominis': ['reto abdominal', 'm'],
  'rectus capitis': ['reto da cabeça', 'm'],
  'rectus femoris': ['reto femoral', 'm'],
  'obliquus capitis': ['oblíquo da cabeça', 'm'],
  'longissimus capitis': ['longuíssimo da cabeça', 'm'],
  'longissimus cervicis': ['longuíssimo do pescoço', 'm'],
  'longissimus thoracis': ['longuíssimo do tórax', 'm'],
  'iliocostalis cervicis': ['iliocostal do pescoço', 'm'],
  'iliocostalis thoracis': ['iliocostal do tórax', 'm'],
  'iliocostalis lumborum': ['iliocostal dos lombos', 'm'],
  'spinalis capitis': ['espinhal da cabeça', 'm'],
  'spinalis cervicis': ['espinhal do pescoço', 'm'],
  'spinalis thoracis': ['espinhal do tórax', 'm'],
  'semispinalis capitis': ['semiespinhal da cabeça', 'm'],
  'semispinalis cervicis': ['semiespinhal do pescoço', 'm'],
  'semispinalis thoracis': ['semiespinhal do tórax', 'm'],
  'levatores costarum': ['levantadores das costelas', 'm'],
  'levator scapulae': ['elevador da escápula', 'm'],
  'levator palpebrae superioris': ['elevador da pálpebra superior', 'm'],
  'flexor digitorum': ['flexor dos dedos', 'm'],
  'extensor digitorum': ['extensor dos dedos', 'm'],
  'flexor pollicis': ['flexor do polegar', 'm'],
  'extensor pollicis': ['extensor do polegar', 'm'],
  'abductor pollicis': ['abdutor do polegar', 'm'],
  'adductor pollicis': ['adutor do polegar', 'm'],
  'opponens pollicis': ['oponente do polegar', 'm'],
  'flexor hallucis': ['flexor do hálux', 'm'],
  'extensor hallucis': ['extensor do hálux', 'm'],
  'abductor hallucis': ['abdutor do hálux', 'm'],
  'adductor hallucis': ['adutor do hálux', 'm'],
  'flexor digiti minimi': ['flexor do dedo mínimo', 'm'],
  'abductor digiti minimi': ['abdutor do dedo mínimo', 'm'],
  'opponens digiti minimi': ['oponente do dedo mínimo', 'm'],
  'extensor indicis': ['extensor do índice', 'm'],
  'flexor carpi radialis': ['flexor radial do carpo', 'm'],
  'flexor carpi ulnaris': ['flexor cubital do carpo', 'm'],
  'extensor carpi radialis': ['extensor radial do carpo', 'm'],
  'extensor carpi ulnaris': ['extensor cubital do carpo', 'm'],
  'pronator teres': ['pronador redondo', 'm'],
  'pronator quadratus': ['pronador quadrado', 'm'],
  'teres major': ['redondo maior', 'm'],
  'teres minor': ['redondo menor', 'm'],
  'pectoralis major': ['grande peitoral', 'm'],
  'pectoralis minor': ['pequeno peitoral', 'm'],
  'gluteus maximus': ['glúteo máximo', 'm'],
  'gluteus medius': ['glúteo médio', 'm'],
  'gluteus minimus': ['glúteo mínimo', 'm'],
  'adductor magnus': ['adutor magno', 'm'],
  'adductor longus': ['adutor longo', 'm'],
  'adductor brevis': ['adutor curto', 'm'],
  'peroneus longus': ['peroneal longo', 'm'],
  'peroneus brevis': ['peroneal curto', 'm'],
  'fibularis longus': ['fibular longo', 'm'],
  'fibularis brevis': ['fibular curto', 'm'],
  'fibularis tertius': ['fibular terceiro', 'm'],
  'tibialis anterior': ['tibial anterior', 'm'],
  'tibialis posterior': ['tibial posterior', 'm'],
  'quadratus lumborum': ['quadrado lombar', 'm'],
  'quadratus plantae': ['quadrado plantar', 'm'],
  'obliquus externus abdominis': ['oblíquo externo do abdómen', 'm'],
  'obliquus internus abdominis': ['oblíquo interno do abdómen', 'm'],
  'transversus abdominis': ['transverso do abdómen', 'm'],
  'index finger': ['dedo indicador', 'm'],
  'middle finger': ['dedo médio', 'm'],
  'ring finger': ['dedo anelar', 'm'],
  'little finger': ['dedo mínimo', 'm'],
  'big toe': ['hálux', 'm'],
  'little toe': ['dedo mínimo do pé', 'm'],
  'second toe': ['segundo dedo do pé', 'm'],
  'third toe': ['terceiro dedo do pé', 'm'],
  'fourth toe': ['quarto dedo do pé', 'm'],
  'white matter': ['substância branca', 'f'],
  'grey matter': ['substância cinzenta', 'f'],
  'gray matter': ['substância cinzenta', 'f'],
  'corpus callosum': ['corpo caloso', 'm'],
  'conus arteriosus': ['cone arterioso', 'm'],
  'taenia libera': ['ténia livre', 'f'],
  'taenia omentalis': ['ténia omental', 'f'],
  'taenia mesocolica': ['ténia mesocólica', 'f'],
  'linea alba': ['linha alba', 'f'],
  'lamina terminalis': ['lâmina terminal', 'f'],
  'stria medullaris': ['estria medular', 'f'],
  'tuber cinereum': ['tuber cinéreo', 'm'],
  'corona ciliaris': ['coroa ciliar', 'f'],
  'dorsalis pedis': ['dorsal do pé', 'f'],
  'arteria princeps pollicis': ['artéria principal do polegar', 'f'],
  'lacrimal lake': ['lago lacrimal', 'm'],
  'anterior chamber': ['câmara anterior', 'f'],
  'posterior chamber': ['câmara posterior', 'f'],
  'spinal cord': ['medula espinhal', 'f'],
  'optic nerve': ['nervo ótico', 'm'],
  'oculomotor nerve': ['nervo oculomotor', 'm'],
  'lower jaw': ['maxilar inferior', 'm'],
  'biceps femoris': ['bíceps femoral', 'm'],
  'longus colli': ['longo do pescoço', 'm'],
  'lateral rectus': ['reto lateral', 'm'],
  'medial rectus': ['reto medial', 'm'],
  'superior oblique': ['oblíquo superior', 'm'],
  'inferior oblique': ['oblíquo inferior', 'm'],
  'conus elasticus': ['cone elástico', 'm'],
  'iliotibial tract': ['trato iliotibial', 'm'],
  'optic tract': ['trato ótico', 'm'],
  'check ligament': ['ligamento de retenção', 'm'],
  'upper jaw': ['maxilar superior', 'm'],
};

export const NOUNS = {
  artery: ['artéria', 'f'],
  arteries: ['artérias', 'f'],
  arteria: ['artéria', 'f'],
  vein: ['veia', 'f'],
  veins: ['veias', 'f'],
  nerve: ['nervo', 'm'],
  nerves: ['nervos', 'm'],
  branch: ['ramo', 'm'],
  branches: ['ramos', 'm'],
  tributary: ['tributária', 'f'],
  trunk: ['tronco', 'm'],
  muscle: ['músculo', 'm'],
  tendon: ['tendão', 'm'],
  ligament: ['ligamento', 'm'],
  bone: ['osso', 'm'],
  cartilage: ['cartilagem', 'f'],
  membrane: ['membrana', 'f'],
  capsule: ['cápsula', 'f'],
  fascia: ['fáscia', 'f'],
  retinaculum: ['retináculo', 'm'],
  raphe: ['rafe', 'f'],
  septum: ['septo', 'm'],
  wall: ['parede', 'f'],
  cavity: ['cavidade', 'f'],
  chamber: ['câmara', 'f'],
  body: ['corpo', 'm'],
  head: ['cabeça', 'f'],
  part: ['parte', 'f'],
  set: ['conjunto', 'm'],
  tree: ['árvore', 'f'],
  division: ['divisão', 'f'],
  segment: ['segmento', 'm'],
  network: ['rede', 'f'],
  arch: ['arco', 'm'],
  ring: ['anel', 'm'],
  plate: ['lâmina', 'f'],
  lamina: ['lâmina', 'f'],
  sulcus: ['sulco', 'm'],
  gyrus: ['giro', 'm'],
  fossa: ['fossa', 'f'],
  lobe: ['lobo', 'm'],
  lobule: ['lóbulo', 'm'],
  hemisphere: ['hemisfério', 'm'],
  ventricle: ['ventrículo', 'm'],
  atrium: ['aurícula', 'f'],
  valve: ['válvula', 'f'],
  cusp: ['cúspide', 'f'],
  leaflet: ['folheto', 'm'],
  vertebra: ['vértebra', 'f'],
  rib: ['costela', 'f'],
  disk: ['disco', 'm'],
  phalanx: ['falange', 'f'],
  finger: ['dedo', 'm'],
  toe: ['dedo do pé', 'm'],
  thumb: ['polegar', 'm'],
  hand: ['mão', 'f'],
  foot: ['pé', 'm'],
  wrist: ['punho', 'm'],
  forearm: ['antebraço', 'm'],
  leg: ['perna', 'f'],
  limb: ['membro', 'm'],
  tooth: ['dente', 'm'],
  gingiva: ['gengiva', 'f'],
  jaw: ['maxilar', 'm'],
  mandible: ['mandíbula', 'f'],
  sternum: ['esterno', 'm'],
  aorta: ['aorta', 'f'],
  duct: ['ducto', 'm'],
  canal: ['canal', 'm'],
  canaliculus: ['canalículo', 'm'],
  junction: ['junção', 'f'],
  bronchus: ['brônquio', 'm'],
  liver: ['fígado', 'm'],
  pancreas: ['pâncreas', 'm'],
  parenchyma: ['parênquima', 'm'],
  colon: ['cólon', 'm'],
  jejunum: ['jejuno', 'm'],
  ileum: ['íleo', 'm'],
  intestine: ['intestino', 'm'],
  mesentery: ['mesentério', 'm'],
  mesocolon: ['mesocólon', 'm'],
  mesoappendix: ['mesoapêndice', 'm'],
  thymus: ['timo', 'm'],
  penis: ['pénis', 'm'],
  retina: ['retina', 'f'],
  lens: ['cristalino', 'm'],
  eyeball: ['globo ocular', 'm'],
  eyelid: ['pálpebra', 'f'],
  ganglion: ['gânglio', 'm'],
  thalamus: ['tálamo', 'm'],
  habenula: ['habénula', 'f'],
  hippocampus: ['hipocampo', 'm'],
  commissure: ['comissura', 'f'],
  fornix: ['fórnix', 'm'],
  forebrain: ['prosencéfalo', 'm'],
  telencephalon: ['telencéfalo', 'm'],
  colliculus: ['colículo', 'm'],
  brachium: ['braço', 'm'],
  stria: ['estria', 'f'],
  matter: ['substância', 'f'],
  cord: ['medula', 'f'],
  hair: ['pelo', 'm'],
  incisor: ['incisivo', 'm'],
  canine: ['canino', 'm'],
  molar: ['molar', 'm'],
  premolar: ['pré-molar', 'm'],
  // Muscles that are a single Latin word in the source.
  trapezius: ['trapézio', 'm'],
  deltoid: ['deltoide', 'm'],
  gastrocnemius: ['gémeo', 'm'],
  soleus: ['sóleo', 'm'],
  sartorius: ['sartório', 'm'],
  gracilis: ['grácil', 'm'],
  popliteus: ['poplíteo', 'm'],
  plantaris: ['plantar', 'm'],
  subscapularis: ['subescapular', 'm'],
  supraspinatus: ['supraespinhoso', 'm'],
  infraspinatus: ['infraespinhoso', 'm'],
  coracobrachialis: ['coracobraquial', 'm'],
  anconeus: ['ancóneo', 'm'],
  brachioradialis: ['braquiorradial', 'm'],
  supinator: ['supinador', 'm'],
  lumbrical: ['lumbrical', 'm'],
  lumbricals: ['lumbricais', 'm'],
  interosseous: ['interósseo', 'm'],
  interossei: ['interósseos', 'm'],
  rotator: ['rotador', 'm'],
  levator: ['elevador', 'm'],
  levatores: ['elevadores', 'm'],
  flexor: ['flexor', 'm'],
  extensor: ['extensor', 'm'],
  abductor: ['abdutor', 'm'],
  adductor: ['adutor', 'm'],
  pronator: ['pronador', 'm'],
  opponens: ['oponente', 'm'],
  intertransversarius: ['intertransversário', 'm'],
  intertransversarii: ['intertransversários', 'm'],
  interspinalis: ['interespinhoso', 'm'],
  interspinales: ['interespinhosos', 'm'],
  cricothyroid: ['cricotiroideo', 'm'],
  thyrohyoid: ['tiro-hioideo', 'm'],
  aryepiglotticus: ['ariepiglótico', 'm'],
  vocalis: ['vocal', 'm'],
  arytenoid: ['aritenoide', 'm'],
  papillary: ['papilar', 'm'],
  trochlea: ['tróclea', 'f'],
  tract: ['trato', 'm'],
  axis: ['áxis', 'm'],
  spinalis: ['espinhal', 'm'],
};

// [masculine, feminine], or one string when the form does not change.
export const ADJECTIVES = {
  left: ['esquerdo', 'esquerda'],
  right: ['direito', 'direita'],
  anterior: 'anterior',
  posterior: 'posterior',
  superior: 'superior',
  inferior: 'inferior',
  medial: 'medial',
  lateral: 'lateral',
  median: ['mediano', 'mediana'],
  central: 'central',
  middle: ['médio', 'média'],
  intermediate: ['intermédio', 'intermédia'],
  proximal: 'proximal',
  distal: 'distal',
  deep: ['profundo', 'profunda'],
  superficial: 'superficial',
  innermost: ['mais interno', 'mais interna'],
  internal: ['interno', 'interna'],
  external: ['externo', 'externa'],
  common: 'comum',
  proper: ['próprio', 'própria'],
  accessory: ['acessório', 'acessória'],
  accessorius: ['acessório', 'acessória'],
  main: 'principal',
  terminal: 'terminal',
  long: ['longo', 'longa'],
  longus: ['longo', 'longa'],
  longi: ['longos', 'longas'],
  short: ['curto', 'curta'],
  brevis: ['curto', 'curta'],
  breves: ['curtos', 'curtas'],
  major: 'maior',
  minor: 'menor',
  minimus: ['mínimo', 'mínima'],
  minimi: ['mínimo', 'mínima'],
  great: 'maior',
  small: ['pequeno', 'pequena'],
  big: ['grande', 'grande'],
  upper: 'superior',
  lower: 'inferior',
  transverse: ['transverso', 'transversa'],
  oblique: ['oblíquo', 'oblíqua'],
  obliquus: ['oblíquo', 'oblíqua'],
  straight: ['reto', 'reta'],
  rectus: ['reto', 'reta'],
  vertical: 'vertical',
  ascending: 'ascendente',
  descending: 'descendente',
  recurrent: 'recorrente',
  perforating: 'perfurante',
  circumflex: ['circunflexo', 'circunflexa'],
  communicating: 'comunicante',
  precommunicating: 'pré-comunicante',
  postcommunicating: 'pós-comunicante',
  segmental: 'segmentar',
  secondary: ['secundário', 'secundária'],
  tendinous: ['tendinoso', 'tendinosa'],
  venous: ['venoso', 'venosa'],
  arterial: 'arterial',
  cardiac: ['cardíaco', 'cardíaca'],
  coronary: ['coronário', 'coronária'],
  ventricular: 'ventricular',
  interventricular: 'interventricular',
  septal: 'septal',
  atrial: 'atrial',
  tricuspid: ['tricúspide', 'tricúspide'],
  mitral: 'mitral',
  aortic: ['aórtico', 'aórtica'],
  pulmonary: 'pulmonar',
  bronchial: ['brônquico', 'brônquica'],
  basal: 'basal',
  mediobasal: 'mediobasal',
  laterobasal: 'laterobasal',
  apical: 'apical',
  lingular: 'lingular',
  lobar: 'lobar',
  hepatic: ['hepático', 'hepática'],
  hepatovenous: ['hepatovenoso', 'hepatovenosa'],
  'pre-hepatic': ['pré-hepático', 'pré-hepática'],
  portal: 'portal',
  biliary: 'biliar',
  pancreatic: ['pancreático', 'pancreática'],
  pancreaticoduodenal: 'pancreaticoduodenal',
  gastroduodenal: 'gastroduodenal',
  celiac: ['celíaco', 'celíaca'],
  splenic: ['esplénico', 'esplénica'],
  mesenteric: ['mesentérico', 'mesentérica'],
  mesocolica: ['mesocólico', 'mesocólica'],
  colic: ['cólico', 'cólica'],
  ileal: 'ileal',
  ileocolic: ['ileocólico', 'ileocólica'],
  ileocecal: 'ileocecal',
  cecal: 'cecal',
  appendicular: 'apendicular',
  sigmoid: ['sigmoide', 'sigmoide'],
  rectal: 'retal',
  renal: 'renal',
  suprarenal: 'suprarrenal',
  ureteric: ['uretérico', 'uretérica'],
  oesophageal: ['esofágico', 'esofágica'],
  esophageal: ['esofágico', 'esofágica'],
  phrenic: ['frénico', 'frénica'],
  musculophrenic: ['musculofrénico', 'musculofrénica'],
  intercostal: 'intercostal',
  subcostal: 'subcostal',
  costal: 'costal',
  sternocostal: 'esternocostal',
  thoracic: ['torácico', 'torácica'],
  thoracis: ['torácico', 'torácica'],
  thoraco: 'toraco',
  'thoraco-acromial': 'toracoacromial',
  thoracodorsal: 'toracodorsal',
  abdominal: 'abdominal',
  lumbar: 'lombar',
  lumborum: 'lombar',
  iliolumbar: 'iliolombar',
  sacral: 'sacral',
  cervical: 'cervical',
  cervicis: 'cervical',
  colli: ['do pescoço', 'do pescoço'],
  capitis: ['da cabeça', 'da cabeça'],
  spinal: 'espinhal',
  spinalis: 'espinhal',
  intervertebral: 'intervertebral',
  epigastric: ['epigástrico', 'epigástrica'],
  femoral: 'femoral',
  femoris: 'femoral',
  genicular: ['geniculado', 'geniculada'],
  tibial: 'tibial',
  fibular: 'fibular',
  peroneal: 'peroneal',
  gluteal: ['glúteo', 'glútea'],
  obturator: ['obturador', 'obturadora'],
  iliac: ['ilíaco', 'ilíaca'],
  iliotibial: 'iliotibial',
  calcaneal: ['calcâneo', 'calcânea'],
  plantar: 'plantar',
  dorsal: 'dorsal',
  dorsalis: 'dorsal',
  palmar: 'palmar',
  digital: 'digital',
  digiti: ['do dedo', 'do dedo'],
  digitorum: ['dos dedos', 'dos dedos'],
  pollicis: ['do polegar', 'do polegar'],
  hallucis: ['do hálux', 'do hálux'],
  indicis: ['do índice', 'do índice'],
  carpi: ['do carpo', 'do carpo'],
  carpal: ['cárpico', 'cárpica'],
  tarsal: ['társico', 'társica'],
  metacarpal: ['metacárpico', 'metacárpica'],
  metatarsal: ['metatársico', 'metatársica'],
  radial: 'radial',
  radialis: 'radial',
  ulnar: ['cubital', 'cubital'],
  ulnaris: ['cubital', 'cubital'],
  brachial: 'braquial',
  brachii: 'braquial',
  humeral: 'humeral',
  clavicular: 'clavicular',
  acromial: 'acromial',
  scapular: 'escapular',
  subscapular: 'subescapular',
  suprascapular: 'supraescapular',
  brachiocephalic: ['braquiocefálico', 'braquiocefálica'],
  pectoral: 'peitoral',
  interosseous: ['interósseo', 'interóssea'],
  collateral: 'colateral',
  marginal: 'marginal',
  diagonal: 'diagonal',
  arcuate: ['arqueado', 'arqueada'],
  angular: 'angular',
  polar: 'polar',
  frontal: 'frontal',
  frontobasal: 'frontobasal',
  prefrontal: 'pré-frontal',
  precentral: 'pré-central',
  postcentral: 'pós-central',
  paracentral: 'paracentral',
  precuneal: 'precuneal',
  supramarginal: 'supramarginal',
  callosomarginal: 'calosomarginal',
  pericallosal: ['pericaloso', 'pericalosa'],
  splenial: 'esplenial',
  insular: 'insular',
  temporal: 'temporal',
  'temporo-occipital': 'temporo-occipital',
  occipital: 'occipital',
  parietal: 'parietal',
  cerebral: 'cerebral',
  cerebellar: ['cerebeloso', 'cerebelosa'],
  vermian: ['vermiano', 'vermiana'],
  pontine: ['pontino', 'pontina'],
  interpeduncular: 'interpeduncular',
  choroidal: ['coroideu', 'coroideia'],
  thalamogeniculate: ['talamogeniculado', 'talamogeniculada'],
  thalamoperforating: 'talamoperfurante',
  hypothalamic: ['hipotalâmico', 'hipotalâmica'],
  geniculate: ['geniculado', 'geniculada'],
  optic: ['ótico', 'ótica'],
  oculomotor: 'oculomotor',
  nasociliary: 'nasociliar',
  ciliary: 'ciliar',
  ciliaris: 'ciliar',
  lacrimal: 'lacrimal',
  supratrochlear: 'supratroclear',
  infratrochlear: 'infratroclear',
  'supra-orbital': 'supraorbitário',
  orbital: ['orbitário', 'orbitária'],
  ethmoidal: 'etmoidal',
  sphenoid: ['esfenoide', 'esfenoide'],
  nasal: 'nasal',
  alar: 'alar',
  corniculate: ['corniculado', 'corniculada'],
  cuneiform: ['cuneiforme', 'cuneiforme'],
  navicular: ['navicular', 'navicular'],
  sesamoid: ['sesamoide', 'sesamoide'],
  pharyngeal: ['faríngeo', 'faríngea'],
  pterygomandibular: 'pterigomandibular',
  'hyo-epiglottic': 'hio-epiglótico',
  'thyro-epiglottic': 'tiro-epiglótico',
  elasticus: ['elástico', 'elástica'],
  vocal: 'vocal',
  suspensory: ['suspensor', 'suspensora'],
  anterolateral: 'anterolateral',
  posteromedial: 'posteromedial',
  posterolateral: 'posterolateral',
  anteromedial: 'anteromedial',
  intermediomedial: 'intermediomedial',
  subsuperior: 'subsuperior',
  caudate: ['caudado', 'caudada'],
  caudal: 'caudal',
  princeps: 'principal',
  white: ['branco', 'branca'],
  ani: ['do ânus', 'do ânus'],
  hemiazygos: ['hemiázigos', 'hemiázigos'],
  azygos: ['ázigos', 'ázigos'],
  medullaris: 'medular',
  cinereum: ['cinéreo', 'cinérea'],
  terminalis: 'terminal',
  libera: 'livre',
  omentalis: 'omental',
  conus: ['cone', 'cone'],
};

export const ORDINALS = {
  first: ['primeiro', 'primeira'],
  second: ['segundo', 'segunda'],
  third: ['terceiro', 'terceira'],
  fourth: ['quarto', 'quarta'],
  fifth: ['quinto', 'quinta'],
  sixth: ['sexto', 'sexta'],
  seventh: ['sétimo', 'sétima'],
  eighth: ['oitavo', 'oitava'],
  ninth: ['nono', 'nona'],
  tenth: ['décimo', 'décima'],
  eleventh: ['décimo primeiro', 'décima primeira'],
  twelfth: ['décimo segundo', 'décima segunda'],
};

// Roman numerals and other tokens that pass through untouched.
export const KEEP = new Set(['i', 'ii', 'iii', 'iv', 'v', 'vi', 'vii', 'viii', 'ix', 'x',
  'xi', 'xii', 'alba', 'check']);
